export const MOCK_PROMPTS = [
  { 
    id: '1', 
    title: 'Cinematic Portrait in Golden Hour', 
    description: 'A stunning cinematic portrait', 
    prompt_text: 'cinematic portrait photography of a beautiful woman, golden hour lighting, warm tones, shallow depth of field, bokeh background, shot on Canon EOS R5, 85mm lens, f/1.4, 8k', 
    negative_prompt: 'blurry, low quality, distorted', 
    model: 'Midjourney V6', 
    ai_tool: 'Midjourney', 
    aspect_ratio: '3:4', 
    style: 'Photorealistic', 
    image_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600', 
    tags: ['portrait', 'cinematic', 'golden hour'], 
    category: 'portrait', 
    is_premium: false, 
    creator_name: 'Sarah Chen', 
    likes_count: 2847, 
    downloads_count: 1234, 
    views_count: 15678, 
    created_at: '2024-01-15T10:00:00Z' 
  },
  { 
    id: '2', 
    title: 'Luxury Sports Car at Night', 
    description: 'Premium sports car in neon city', 
    prompt_text: 'luxury sports car, Lamborghini Aventador, parked on wet city street at night, neon reflections, rain puddles, cinematic lighting, 8k ultra detailed', 
    negative_prompt: 'low quality, blurry', 
    model: 'Midjourney V6', 
    ai_tool: 'Midjourney', 
    aspect_ratio: '16:9', 
    style: 'Cinematic', 
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600', 
    tags: ['cars', 'luxury', 'night'], 
    category: 'cars', 
    is_premium: true, 
    creator_name: 'Marcus Johnson', 
    likes_count: 1923, 
    downloads_count: 876, 
    views_count: 12453, 
    created_at: '2024-01-14T15:30:00Z' 
  },
  { 
    id: '3', 
    title: 'Japanese Garden Interior', 
    description: 'Peaceful Japanese garden room', 
    prompt_text: 'Japanese zen interior design, traditional wooden architecture, indoor garden with bonsai trees, natural sunlight, minimalist furniture, 8k', 
    negative_prompt: 'modern, western, cluttered', 
    model: 'SDXL', 
    ai_tool: 'Stable Diffusion', 
    aspect_ratio: '16:9', 
    style: 'Photorealistic', 
    image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600', 
    tags: ['interior', 'japanese', 'zen'], 
    category: 'interior', 
    is_premium: false, 
    creator_name: 'Yuki Tanaka', 
    likes_count: 1567, 
    downloads_count: 654, 
    views_count: 8934, 
    created_at: '2024-01-13T09:15:00Z' 
  },
  { 
    id: '4', 
    title: 'Anime Girl with Cherry Blossoms', 
    description: 'Beautiful anime character', 
    prompt_text: 'anime girl with long flowing hair, cherry blossom petals falling, spring garden background, studio ghibli style, vibrant colors, detailed eyes, 4k', 
    negative_prompt: 'low quality, bad anatomy', 
    model: 'Midjourney V6', 
    ai_tool: 'Midjourney', 
    aspect_ratio: '3:4', 
    style: 'Anime', 
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600', 
    tags: ['anime', 'cherry blossom', 'spring'], 
    category: 'anime', 
    is_premium: false, 
    creator_name: 'Hiroshi Art', 
    likes_count: 3245, 
    downloads_count: 1876, 
    views_count: 23456, 
    created_at: '2024-01-11T11:45:00Z' 
  },
  { 
    id: '5', 
    title: 'Gourmet Food Photography', 
    description: 'Artistically plated gourmet dish', 
    prompt_text: 'gourmet food photography, seared wagyu beef steak, fresh herbs, microgreens, artistic plating, dark moody background, dramatic side lighting, 8k', 
    negative_prompt: 'cheap, fast food, blurry', 
    model: 'Flux Pro', 
    ai_tool: 'Flux', 
    aspect_ratio: '1:1', 
    style: 'Photorealistic', 
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600', 
    tags: ['food', 'gourmet', 'wagyu'], 
    category: 'food', 
    is_premium: true, 
    creator_name: 'Chef Antoine', 
    likes_count: 945, 
    downloads_count: 432, 
    views_count: 6782, 
    created_at: '2024-01-12T14:00:00Z' 
  },
  { 
    id: '6', 
    title: 'Luxury Villa Exterior', 
    description: 'Modern luxury villa with pool', 
    prompt_text: 'modern luxury villa, infinity pool, mountain landscape view, sunset lighting, architectural photography, glass and concrete design, 8k', 
    negative_prompt: 'old, dilapidated, dark', 
    model: 'DALL-E 3', 
    ai_tool: 'DALL-E 3', 
    aspect_ratio: '16:9', 
    style: 'Photorealistic', 
    image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600', 
    tags: ['luxury', 'architecture', 'villa'], 
    category: 'luxury', 
    is_premium: true, 
    creator_name: 'Elena Martinez', 
    likes_count: 1234, 
    downloads_count: 567, 
    views_count: 9876, 
    created_at: '2024-01-10T16:20:00Z' 
  },
];

export const CATEGORIES = [
  { name: 'profile photo', icon: '📸', count: 2847 },
  { name: 'Anime',         icon: '🎨', count: 1923 },
  { name: 'girls',         icon: '👩', count: 856 },
  { name: 'Boys',          icon: '👨', count: 945 },
  { name: 'Couples',       icon: '💑', count: 567 },
  { name: 'Wallpaper',     icon: '🖼️', count: 1234 },
  { name: 'Fantasy',       icon: '🧙', count: 1567 },
  { name: 'Portrait',      icon: '👤', count: 2134 },
];